#!/usr/bin/env python3
"""Fetch fixed npm packages, verify registry integrity, build the dashboard
vendor assets, embed the fonts, and record their digests.

echarts.min.js is a custom ECharts build with only what the renderer uses
(assets/renderer/render.js): line, bar and gauge series, the cartesian grid
with legacy containLabel layout, and the SVG renderer. esbuild-wasm bundles
it, so the output is byte-identical on every machine with Node.js.

The two Inter WOFF2 fonts are base64 data URIs in the @font-face lines at the
top of assets/renderer/style.css, so the plugin ships no binary files. The rest
of the stylesheet is hand-written and kept as is.
"""
import base64
import hashlib
import io
import json
from pathlib import Path
import subprocess
import tarfile
import tempfile
import urllib.request

ROOT = Path(__file__).resolve().parents[1] / 'skills/screenrig-dashboard'
VENDOR = ROOT / 'assets/vendor'
STYLE = ROOT / 'assets/renderer/style.css'
NOTICES = 'THIRD_PARTY_NOTICES.txt'
# name: (exact version, embedded font files by weight, license files for the notices)
PACKAGES = {
    'echarts': ('6.1.0', {}, ['LICENSE', 'NOTICE', 'licenses/LICENSE-d3']),
    'zrender': ('6.1.0', {}, ['LICENSE']),
    'tslib': ('2.3.0', {}, ['LICENSE.txt']),
    '@fontsource/inter': ('5.3.0', {400: 'files/inter-latin-400-normal.woff2',
                                    600: 'files/inter-latin-600-normal.woff2'}, ['LICENSE']),
    # Build tool only; nothing from it ships.
    'esbuild-wasm': ('0.28.2', {}, []),
}
FONT_FACE = '@font-face{font-family:Inter;'
ENTRY = """\
import { use } from 'echarts/core';
import { BarChart, GaugeChart, LineChart } from 'echarts/charts';
import { GridComponent } from 'echarts/components';
import { LegacyGridContainLabel } from 'echarts/features';
import { SVGRenderer } from 'echarts/renderers';
use([SVGRenderer, LineChart, BarChart, GaugeChart, GridComponent, LegacyGridContainLabel]);
export * from 'echarts/core';
"""
BANNER = ('/*! Apache ECharts 6.1.0 with zrender 6.1.0, custom build: line, bar, gauge, grid, SVG renderer. '
          'Licenses: THIRD_PARTY_NOTICES.txt */')


def fetch(name, version, pinned):
    metadata = json.load(urllib.request.urlopen(f'https://registry.npmjs.org/{name}/{version}'))
    dist = metadata['dist']
    archive = urllib.request.urlopen(dist['tarball']).read()
    actual = 'sha512-' + base64.b64encode(hashlib.sha512(archive).digest()).decode()
    if actual != dist['integrity'] or pinned.get((name, version), actual) != actual:
        raise RuntimeError(f'Package integrity mismatch: {name}@{version}.')
    return archive, {'name': name, 'version': version, 'url': dist['tarball'], 'integrity': actual}


def main():
    lock_path = ROOT / 'dependencies.lock.json'
    previous = json.loads(lock_path.read_text()) if lock_path.exists() else {'packages': []}
    pinned = {(p['name'], p['version']): p['integrity'] for p in previous['packages']}
    lock = {'format': 'screenrig.dashboard-dependencies/v1', 'packages': [], 'assets': {}}
    outputs = {}
    fonts = {}
    notices = ['Third-party software in this skill.\n\n'
               'echarts.min.js is a custom build of Apache ECharts 6.1.0 with zrender 6.1.0 and tslib 2.3.0,\n'
               'generated by scripts/sync-dashboard-assets.py. The Inter regular (400) and semibold (600)\n'
               'fonts in ../renderer/style.css are WOFF2 files from @fontsource/inter 5.3.0, embedded as\n'
               'base64 data URIs.\n']
    with tempfile.TemporaryDirectory(prefix='screenrig-dashboard-assets-') as temporary:
        work = Path(temporary)
        for name, (version, files, licenses) in PACKAGES.items():
            archive, entry = fetch(name, version, pinned)
            lock['packages'].append(entry)
            package = work / 'node_modules' / name
            package.parent.mkdir(parents=True, exist_ok=True)
            with tarfile.open(fileobj=io.BytesIO(archive), mode='r:gz') as tar:
                tar.extractall(work / 'unpacked' / name, filter='data')
            (work / 'unpacked' / name / 'package').rename(package)
            for weight, source in files.items():
                fonts[weight] = (package / source).read_bytes()
            for source in licenses:
                text = (package / source).read_text(encoding='utf-8').strip()
                notices.append(f'\n{"=" * 72}\n{name} {version}: {source}\n{"=" * 72}\n\n{text}\n')
        (work / 'entry.js').write_text(ENTRY)
        subprocess.run(['node', 'node_modules/esbuild-wasm/bin/esbuild', 'entry.js', '--bundle', '--minify',
                        '--format=iife', '--global-name=echarts', '--define:process.env.NODE_ENV="production"',
                        '--legal-comments=none', '--charset=utf8', f'--banner:js={BANNER}',
                        '--log-level=warning', '--outfile=echarts.min.js'], cwd=work, check=True)
        outputs['echarts.min.js'] = (work / 'echarts.min.js').read_bytes()
    outputs[NOTICES] = ''.join(notices).encode()
    VENDOR.mkdir(parents=True, exist_ok=True)
    for stale in VENDOR.iterdir():
        if stale.name not in outputs:
            stale.unlink()
    for filename, data in sorted(outputs.items()):
        if len(data) > 2 * 1024 * 1024:
            raise RuntimeError('Asset exceeds the plugin per-file budget.')
        (VENDOR / filename).write_bytes(data)
        lock['assets'][filename] = hashlib.sha256(data).hexdigest()
    faces = ''.join(f"{FONT_FACE}src:url('data:font/woff2;base64,{base64.b64encode(data).decode()}');"
                    f'font-weight:{weight};font-display:block}}\n' for weight, data in sorted(fonts.items()))
    rules = [line for line in STYLE.read_text().splitlines(keepends=True) if not line.startswith(FONT_FACE)]
    STYLE.write_text(faces + ''.join(rules))
    lock['fonts'] = {f'inter-{weight}.woff2': hashlib.sha256(data).hexdigest() for weight, data in sorted(fonts.items())}
    lock['requirements_sha256'] = hashlib.sha256((ROOT / 'requirements.lock').read_bytes()).hexdigest()
    lock_path.write_text(json.dumps(lock, indent=2) + '\n')
    print('Dashboard asset sync and integrity checks passed.')


if __name__ == '__main__':
    main()
